apiVersion: apps/v1
kind: Deployment
metadata:
  name: axis-cronclient
  namespace: default
  labels:
    app: axis-cronclient
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: axis-cronclient
  template:
    metadata:
      labels:
        app: axis-cronclient
    spec:
      containers:
        - name: axis-cronclient
          image: yintech/axis-cronclient:v1
          lifecycle:
            preStop:
              exec:
                command: ["sh","-c","sleep 2"]
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
          volumeMounts:
            - name: timezone
              mountPath: /etc/localtime
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
