version: '3'

####### 目前只有定时任务服务端、客户端及定时任务队列WEBUI ##################

services:
  #asynqmon asynq延迟队列、定时队列的webui
  asynqmon:
    image: hibiken/asynqmon:latest
    container_name: asynqmon
    ports:
      - 8980:8080
    command:
      - '--redis-addr=192.168.19.98:6379'
      - '--redis-password=tiantong99.c0m'
    restart: always
    networks:
      -  axis_net

  #定时任务服务端
  axis-cronserver:
    image: yintech/axis-cronserver:v1
    container_name: axis-cronserver
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    networks:
      - axis_net

  #定时任务客户端
  axis-cronclient:
    image: yintech/axis-cronclient:v1
    container_name: axis-cronclient
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    networks:
      - axis_net
    depends_on:
      - axis-cronserver
      -
networks:
  axis_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.100.0.0/16

